import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'sk' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Enhanced translations with more keys
const translations: Record<string, Record<string, string>> = {
  sk: {
    'save.later': 'Uložiť a pokračovať neskôr',
    'back': 'Späť',
    'next': 'Ďalej',
    'step': 'Krok',
    'remaining.steps': 'Zostáva krokov',
    'remaining.time': 'Zostáva cca',
    'minutes': 'minút',
    'last.step': 'Posledný krok',
    'need.help': 'Potrebujete pomôcť?',
    'contact.us': 'Kontaktujte nás na',
    'welcome': 'Vitajte v Utopia',
    'welcome.subtitle': 'Vaša cesta k inteligentnejšiemu predaju začína tu',
    'start.onboarding': 'Začať onboarding',
    'select.business.type': 'Vyberte typ vášho podnikania',
    'business.type.subtitle': 'Tento výber nám pomôže prispôsobiť riešenie vašim potrebám',
    'continue': 'Pokračovať',
    'onboarding.process': 'Proces onboardingu',
    'activate.account': 'Aktivujte svoj účet',
    'activate.subtitle': 'Dokončite zostávajúce kroky pre aktiváciu',
    'back.to.dashboard': 'Späť na dashboard',
    'tasks.remaining': 'úloh zostáva',
    'select.country': 'Vyberte krajinu',
    'country.subtitle': 'Lokalizujeme služby podľa vašej krajiny',
    'create.account': 'Vytvorte si účet',
    'account.subtitle': 'Potrebujeme od vás len pár základných údajov',
    'verify.phone': 'Overte telefónne číslo',
    'phone.subtitle': 'Pošleme vám SMS kód pre overenie',
    'send.code': 'Poslať kód',
    'verification.code': 'Verifikačný kód',
    'verify.code': 'Overiť kód',
    'enter.code': 'Zadajte 4-miestny kód, ktorý sme vám poslali SMS správou',
    'products.select': 'Výber riešenia',
    'products.subtitle': 'Čo potrebujete? Vyberte si jedno alebo viac riešení',
    'continue.to.portal': 'Pokračovať do portálu',
    'hello': 'Dobrý deň',
    'verify.company': 'Overenie spoločnosti',
    'complete.profile': 'Dokončite svoj profil',
    'back.to.business': 'Späť k podnikaniu',
    'why.needed': 'Prečo to potrebujeme?',
    'hide.info': 'Skryť informáciu',
    'light.mode': 'Svetlý režim',
    'dark.mode': 'Tmavý režim',
    'light': 'Svetlý',
    'dark': 'Tmavý',
    'all.rights.reserved': 'Všetky práva vyhradené',
    'first.name': 'Meno',
    'last.name': 'Priezvisko',
    'email': 'Email',
    'phone': 'Telefónne číslo',
    'password': 'Heslo',
    'confirm.password': 'Potvrďte heslo',
    'agree.terms': 'Súhlasím s podmienkami',
    'personal.info': 'Osobné údaje',
    'company.info': 'Firemné údaje',
    'beneficial.owners': 'Koneční užívatelia výhod',
    'billing': 'Fakturačné údaje',
    'sign': 'Podpis',
    'company.name': 'Názov spoločnosti',
    'company.id': 'IČO',
    'tax.id': 'DIČ',
    'vat.id': 'IČ DPH',
    'address': 'Adresa',
    'city': 'Mesto',
    'postal.code': 'PSČ',
    'country': 'Krajina',
    'chat.with.us': 'Chatujte s nami',
    'how.can.we.help': 'Ako Vám môžeme pomôcť?',
    'slovak.language': 'Slovenský jazyk',
    'english.language': 'Anglický jazyk',
    'add.location': 'Pridať prevádzku',
    'remove.location': 'Odstrániť prevádzku',
    'business.locations': 'Prevádzkarne',
    'wifi': 'WiFi',
    'sim.card': 'SIM karta',
    'connectivity': 'Pripojenie',
    'payment.terminal': 'Platobný terminál',
    'payment.gateway': 'Platobná brána',
    'charging.station': 'Nabíjacia stanica',
    'pos.system': 'Pokladničný systém',
    'select.solution.type': 'Vyberte typ riešenia',
    'dashboard': 'Dashboard',
    'transactions': 'Transakcie',
    'customers': 'Zákazníci',
    'reports': 'Reporty',
    'settings': 'Nastavenia',
    'logout': 'Odhlásiť sa',
    'profile': 'Profil',
    'notifications': 'Notifikácie',
    'help': 'Pomoc',
    'slovakia': 'Slovensko',
    'czech.republic': 'Česká republika',
    'austria': 'Rakúsko',
    'hungary': 'Maďarsko',
    'poland': 'Poľsko',
    'germany': 'Nemecko',
    'united.kingdom': 'Spojené kráľovstvo',
    'business.name': 'Názov prevádzky',
    'business.address': 'Adresa prevádzky',
    'opening.hours': 'Otváracie hodiny',
    'is.seasonal': 'Sezónna prevádzka',
    'season.duration': 'Trvanie sezóny',
    'estimated.annual.turnover': 'Odhadovaný ročný obrat',
    'average.transaction': 'Priemerná výška transakcie',
    'expected.card.turnover': 'Očakávaný obrat z kariet',
    'business.type': 'Typ prevádzky',
    'business.subject': 'Predmet podnikania',
    'weeks': 'týždňov',
    'yes': 'Áno',
    'no': 'Nie',
    'add': 'Pridať',
    'remove': 'Odstrániť',
    'save': 'Uložiť',
    'cancel': 'Zrušiť',
    'brick.and.mortar': 'Kamenná',
    'mobile': 'Mobilná',
    'seasonal_business': 'Sezónna',
    'other': 'Iné',
    'devices': 'Zariadenia',
    'licences': 'Licencie',
    'services': 'Služby',
    'quantity': 'Počet kusov',
    'purchase.type': 'Typ nákupu',
    'rental': 'Prenájom',
    'purchase': 'Kúpa',
    'commitment': 'Viazanosť',
    'payment.frequency': 'Frekvencia platby',
    'monthly': 'Mesačne',
    'yearly': 'Ročne',
    'seasonal.payment': 'Sezónne',
    'from.turnover': 'Z obratu',
    'payment.methods': 'Platobné metódy',
    'additional.services': 'Doplnkové služby',
    'additional.info': 'Dodatočné informácie',
    'months': 'mesiacov',
    'payment.terminal.description': 'Terminál pre akceptáciu platobných kariet priamo na predajni',
    'payment.gateway.description': 'Riešenie pre online platby na vašom e-shope',
    'pos.system.description': 'Kompletný pokladničný systém s eKasou',
    'charging.station.description': 'Nabíjacia stanica pre elektromobily',
    'monthly.transactions': 'Mesačné transakcie',
    'devices.status': 'Stav zariadení',
    'last.active': 'Posledná aktivita',
    'contact.support': 'Kontaktovať podporu',
    'remaining.tasks': 'Zostávajúce úlohy',
    'continue.onboarding': 'Pokračovať v onboardingu',
    'onboarding.complete': 'Onboarding dokončený!',
    'onboarding.complete.subtitle': 'Môžete začať používať všetky funkcie platformy.',
    'user': 'Používateľ',
    'view.all.notifications': 'Zobraziť všetky notifikácie',
    'mobile.pos': 'Mobilná pokladňa',
    'mobile.pos.description': 'Aplikácia pre predaj kdekoľvek ste, bez potreby fixného terminálu',
    'retail.solution': 'Maloobchodné riešenie',
    'retail.solution.description': 'Kompletné riešenie pre maloobchodné prevádzky zahŕňajúce pokladňu a sklad',
    'not.sure.yet': 'Ešte neviem',
    'not.sure.description': 'Pomôžeme vám s výberom riešenia neskôr',
    'enter.full.name': 'Vaše meno a priezvisko',
    'email.placeholder': 'Váš email',
    'full.name': 'Meno a priezvisko',
  },
  en: {
    'save.later': 'Save and continue later',
    'back': 'Back',
    'next': 'Next',
    'step': 'Step',
    'remaining.steps': 'Steps remaining',
    'remaining.time': 'Approx.',
    'minutes': 'minutes left',
    'last.step': 'Last step',
    'need.help': 'Need help?',
    'contact.us': 'Contact us at',
    'welcome': 'Welcome to Utopia',
    'welcome.subtitle': 'Your journey to smarter selling starts here',
    'start.onboarding': 'Start onboarding',
    'select.business.type': 'Select your business type',
    'business.type.subtitle': 'This will help us customize the solution to your needs',
    'continue': 'Continue',
    'onboarding.process': 'Onboarding process',
    'activate.account': 'Activate your account',
    'activate.subtitle': 'Complete the remaining steps to activate',
    'back.to.dashboard': 'Back to dashboard',
    'tasks.remaining': 'tasks remaining',
    'select.country': 'Select country',
    'country.subtitle': 'We will localize services based on your country',
    'create.account': 'Create an account',
    'account.subtitle': 'We need just a few basic details from you',
    'verify.phone': 'Verify phone number',
    'phone.subtitle': 'We will send you an SMS code for verification',
    'send.code': 'Send code',
    'verification.code': 'Verification code',
    'verify.code': 'Verify code',
    'enter.code': 'Enter the 4-digit code we sent you by SMS',
    'products.select': 'Select solutions',
    'products.subtitle': 'What do you need? Select one or more solutions',
    'continue.to.portal': 'Continue to portal',
    'hello': 'Hello',
    'verify.company': 'Verify company',
    'complete.profile': 'Complete your profile',
    'back.to.business': 'Back to business',
    'why.needed': 'Why do we need this?',
    'hide.info': 'Hide information',
    'light.mode': 'Light mode',
    'dark.mode': 'Dark mode',
    'light': 'Light',
    'dark': 'Dark',
    'all.rights.reserved': 'All rights reserved',
    'first.name': 'First name',
    'last.name': 'Last name',
    'email': 'Email',
    'phone': 'Phone number',
    'password': 'Password',
    'confirm.password': 'Confirm password',
    'agree.terms': 'I agree to the terms',
    'personal.info': 'Personal information',
    'company.info': 'Company information',
    'beneficial.owners': 'Beneficial owners',
    'billing': 'Billing information',
    'sign': 'Signature',
    'company.name': 'Company name',
    'company.id': 'Company ID',
    'tax.id': 'Tax ID',
    'vat.id': 'VAT ID',
    'address': 'Address',
    'city': 'City',
    'postal.code': 'Postal code',
    'country': 'Country',
    'chat.with.us': 'Chat with us',
    'how.can.we.help': 'How can we help you?',
    'slovak.language': 'Slovak language',
    'english.language': 'English language',
    'add.location': 'Add location',
    'remove.location': 'Remove location',
    'business.locations': 'Business locations',
    'wifi': 'WiFi',
    'sim.card': 'SIM card',
    'connectivity': 'Connectivity',
    'payment.terminal': 'Payment Terminal',
    'payment.gateway': 'Payment Gateway',
    'charging.station': 'Charging Station',
    'pos.system': 'Point of Sale System',
    'select.solution.type': 'Select solution type',
    'dashboard': 'Dashboard',
    'transactions': 'Transactions',
    'customers': 'Customers',
    'reports': 'Reports',
    'settings': 'Settings',
    'logout': 'Logout',
    'profile': 'Profile',
    'notifications': 'Notifications',
    'help': 'Help',
    'slovakia': 'Slovakia',
    'czech.republic': 'Czech Republic',
    'austria': 'Austria',
    'hungary': 'Hungary',
    'poland': 'Poland',
    'germany': 'Germany',
    'united.kingdom': 'United Kingdom',
    'business.name': 'Business name',
    'business.address': 'Business address',
    'opening.hours': 'Opening hours',
    'is.seasonal': 'Seasonal business',
    'season.duration': 'Season duration',
    'estimated.annual.turnover': 'Estimated annual turnover',
    'average.transaction': 'Average transaction amount',
    'expected.card.turnover': 'Expected card turnover',
    'business.type': 'Business type',
    'business.subject': 'Business subject',
    'weeks': 'weeks',
    'yes': 'Yes',
    'no': 'No',
    'add': 'Add',
    'remove': 'Remove',
    'save': 'Save',
    'cancel': 'Cancel',
    'brick.and.mortar': 'Brick and mortar',
    'mobile': 'Mobile',
    'seasonal_business': 'Seasonal',
    'other': 'Other',
    'devices': 'Devices',
    'licences': 'Licenses',
    'services': 'Services',
    'quantity': 'Quantity',
    'purchase.type': 'Purchase type',
    'rental': 'Rental',
    'purchase': 'Purchase',
    'commitment': 'Commitment',
    'payment.frequency': 'Payment frequency',
    'monthly': 'Monthly',
    'yearly': 'Yearly',
    'seasonal.payment': 'Seasonal',
    'from.turnover': 'From turnover',
    'payment.methods': 'Payment methods',
    'additional.services': 'Additional services',
    'additional.info': 'Additional information',
    'months': 'months',
    'payment.terminal.description': 'Terminal for accepting payment cards directly in your store',
    'payment.gateway.description': 'Solution for online payments on your e-commerce site',
    'pos.system.description': 'Complete point of sale system with electronic cash register',
    'charging.station.description': 'Charging station for electric vehicles',
    'monthly.transactions': 'Monthly Transactions',
    'devices.status': 'Devices Status',
    'last.active': 'Last active',
    'contact.support': 'Contact Support',
    'remaining.tasks': 'Remaining Tasks',
    'continue.onboarding': 'Continue onboarding',
    'onboarding.complete': 'Onboarding complete!',
    'onboarding.complete.subtitle': 'You can now use all platform features.',
    'user': 'User',
    'view.all.notifications': 'View all notifications',
    'mobile.pos': 'Mobile POS',
    'mobile.pos.description': 'Application for selling wherever you are, without a fixed terminal',
    'retail.solution': 'Retail Solution',
    'retail.solution.description': 'Complete solution for retail operations including POS and inventory',
    'not.sure.yet': 'Not sure yet',
    'not.sure.description': 'We\'ll help you choose later',
    'enter.full.name': 'Your full name',
    'email.placeholder': 'Your email',
    'full.name': 'Full name',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('sk');

  // Load language from localStorage
  useEffect(() => {
    const savedLanguage = localStorage.getItem('utopiaLanguage') as Language;
    if (savedLanguage && (savedLanguage === 'sk' || savedLanguage === 'en')) {
      setLanguage(savedLanguage);
    }
  }, []);

  // Save language to localStorage
  useEffect(() => {
    localStorage.setItem('utopiaLanguage', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
