// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozybtpofuykvixhwgqxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96eWJ0cG9mdXlrdml4aHdncXhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NzI5MTYsImV4cCI6MjA2NDQ0ODkxNn0.UhBCh84_YdlLM-lD9qSjHWMJIiufFlY7h0rouVLNDGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);